export const memberData = [
  {
    "memberId": 1,
    "firstName": "John",
    "lastName": "Smith",
    "email": "john.smith@example.com",
    "phone": "732-555-2001",
    "membershipType": "Gold",
    "joinDate": "2024-01-10",
    "active": true,
    "assignedTrainer": null,
    "monthlyFee": 50,
    "paymentStatus": "Paid"
  },
  {
    "memberId": 2,
    "firstName": "Michael",
    "lastName": "Johnson",
    "email": "michael.johnson@example.com",
    "phone": "732-555-2002",
    "membershipType": "Premium",
    "joinDate": "2024-02-05",
    "active": true,
    "assignedTrainer": "Chris Adams",
    "monthlyFee": 90,
    "paymentStatus": "Paid"
  },
  {
    "memberId": 3,
    "firstName": "David",
    "lastName": "Williams",
    "email": "david.williams@example.com",
    "phone": "732-555-2003",
    "membershipType": "Gold",
    "joinDate": "2023-12-20",
    "active": true,
    "assignedTrainer": null,
    "monthlyFee": 50,
    "paymentStatus": "Due"
  },
  {
    "memberId": 4,
    "firstName": "James",
    "lastName": "Brown",
    "email": "james.brown@example.com",
    "phone": "732-555-2004",
    "membershipType": "Premium",
    "joinDate": "2024-03-01",
    "active": true,
    "assignedTrainer": "Daniel Lee",
    "monthlyFee": 90,
    "paymentStatus": "Paid"
  },
  {
    "memberId": 5,
    "firstName": "Robert",
    "lastName": "Jones",
    "email": "robert.jones@example.com",
    "phone": "732-555-2005",
    "membershipType": "Gold",
    "joinDate": "2023-11-11",
    "active": false,
    "assignedTrainer": null,
    "monthlyFee": 50,
    "paymentStatus": "Overdue"
  },
  {
    "memberId": 6,
    "firstName": "Daniel",
    "lastName": "Garcia",
    "email": "daniel.garcia@example.com",
    "phone": "732-555-2006",
    "membershipType": "Premium",
    "joinDate": "2024-01-22",
    "active": true,
    "assignedTrainer": "Mark Wilson",
    "monthlyFee": 90,
    "paymentStatus": "Paid"
  },
  {
    "memberId": 7,
    "firstName": "Matthew",
    "lastName": "Miller",
    "email": "matthew.miller@example.com",
    "phone": "732-555-2007",
    "membershipType": "Gold",
    "joinDate": "2023-10-15",
    "active": true,
    "assignedTrainer": null,
    "monthlyFee": 50,
    "paymentStatus": "Paid"
  },
  {
    "memberId": 8,
    "firstName": "Andrew",
    "lastName": "Davis",
    "email": "andrew.davis@example.com",
    "phone": "732-555-2008",
    "membershipType": "Premium",
    "joinDate": "2024-02-18",
    "active": true,
    "assignedTrainer": "Chris Adams",
    "monthlyFee": 90,
    "paymentStatus": "Due"
  },
  {
    "memberId": 9,
    "firstName": "Joseph",
    "lastName": "Rodriguez",
    "email": "joseph.rodriguez@example.com",
    "phone": "732-555-2009",
    "membershipType": "Gold",
    "joinDate": "2023-09-09",
    "active": false,
    "assignedTrainer": null,
    "monthlyFee": 50,
    "paymentStatus": "Overdue"
  },
  {
    "memberId": 10,
    "firstName": "Christopher",
    "lastName": "Martinez",
    "email": "chris.martinez@example.com",
    "phone": "732-555-2010",
    "membershipType": "Premium",
    "joinDate": "2024-03-05",
    "active": true,
    "assignedTrainer": "Daniel Lee",
    "monthlyFee": 90,
    "paymentStatus": "Paid"
  },
  {
    "memberId": 11,
    "firstName": "Mary",
    "lastName": "Hernandez",
    "email": "mary.hernandez@example.com",
    "phone": "732-555-2011",
    "membershipType": "Gold",
    "joinDate": "2023-08-01",
    "active": true,
    "assignedTrainer": null,
    "monthlyFee": 50,
    "paymentStatus": "Paid"
  },
  {
    "memberId": 12,
    "firstName": "Sarah",
    "lastName": "Lopez",
    "email": "sarah.lopez@example.com",
    "phone": "732-555-2012",
    "membershipType": "Premium",
    "joinDate": "2024-01-30",
    "active": true,
    "assignedTrainer": "Mark Wilson",
    "monthlyFee": 90,
    "paymentStatus": "Paid"
  },
  {
    "memberId": 13,
    "firstName": "Elizabeth",
    "lastName": "Gonzalez",
    "email": "elizabeth.g@example.com",
    "phone": "732-555-2013",
    "membershipType": "Gold",
    "joinDate": "2023-07-14",
    "active": true,
    "assignedTrainer": null,
    "monthlyFee": 50,
    "paymentStatus": "Due"
  },
  {
    "memberId": 14,
    "firstName": "Anna",
    "lastName": "Wilson",
    "email": "anna.wilson@example.com",
    "phone": "732-555-2014",
    "membershipType": "Premium",
    "joinDate": "2024-02-22",
    "active": true,
    "assignedTrainer": "Chris Adams",
    "monthlyFee": 90,
    "paymentStatus": "Paid"
  },
  {
    "memberId": 15,
    "firstName": "Rebecca",
    "lastName": "Anderson",
    "email": "rebecca.anderson@example.com",
    "phone": "732-555-2015",
    "membershipType": "Gold",
    "joinDate": "2023-06-10",
    "active": false,
    "assignedTrainer": null,
    "monthlyFee": 50,
    "paymentStatus": "Overdue"
  },
  {
    "memberId": 16,
    "firstName": "Rachel",
    "lastName": "Thomas",
    "email": "rachel.thomas@example.com",
    "phone": "732-555-2016",
    "membershipType": "Premium",
    "joinDate": "2024-03-10",
    "active": true,
    "assignedTrainer": "Daniel Lee",
    "monthlyFee": 90,
    "paymentStatus": "Paid"
  },
  {
    "memberId": 17,
    "firstName": "Grace",
    "lastName": "Taylor",
    "email": "grace.taylor@example.com",
    "phone": "732-555-2017",
    "membershipType": "Gold",
    "joinDate": "2023-05-18",
    "active": true,
    "assignedTrainer": null,
    "monthlyFee": 50,
    "paymentStatus": "Paid"
  },
  {
    "memberId": 18,
    "firstName": "Hannah",
    "lastName": "Moore",
    "email": "hannah.moore@example.com",
    "phone": "732-555-2018",
    "membershipType": "Premium",
    "joinDate": "2024-01-12",
    "active": true,
    "assignedTrainer": "Mark Wilson",
    "monthlyFee": 90,
    "paymentStatus": "Due"
  },
  {
    "memberId": 19,
    "firstName": "Martha",
    "lastName": "Jackson",
    "email": "martha.jackson@example.com",
    "phone": "732-555-2019",
    "membershipType": "Gold",
    "joinDate": "2023-04-09",
    "active": true,
    "assignedTrainer": null,
    "monthlyFee": 50,
    "paymentStatus": "Paid"
  },
  {
    "memberId": 20,
    "firstName": "Abigail",
    "lastName": "White",
    "email": "abigail.white@example.com",
    "phone": "732-555-2020",
    "membershipType": "Premium",
    "joinDate": "2024-02-28",
    "active": true,
    "assignedTrainer": "Chris Adams",
    "monthlyFee": 90,
    "paymentStatus": "Paid"
  }
]
export const staffData = [
  {
    "memberId": 1,
    "firstName": "George",
    "lastName": "Washington",
    "contact": "732-555-2001",
    "email": "george.washington@example.com",
    "designation": "Store Manager",
    
  },
  {
     "memberId": 2,
    "firstName": "Teddy",
    "lastName": "Roosevelt",
    "contact": "732-555-2002",
    "email": "teddy.roosevelt@example.com",
    "designation": "Personal Trainer",
  },
  {
     "memberId": 3,
    "firstName": "Benjamin",
    "lastName": "Franklin",
    "contact": "732-555-2003",
    "email": "benjamin.franklin@example.com",
    "designation": "Front desk Associate",
  },
  { "memberId": 4,
    "firstName": "Thomas",
    "lastName": "Edison",
    "contact": "732-555-2004",
    "email": "thomas.edison@example.com",
    "designation": "IT help",
  },
  {
    "memberId": 5,
    "firstName": "Abraham",
    "lastName": "Lincoln",
    "contact": "732-555-2005",
    "email": "abraham.lincoln@example.com",
    "designation": "Janitorial staff",
  },
  {
    "memberId": 6,
    "firstName": "Justin",
    "lastName": "Trudeau",
    "contact": "732-555-2006",
    "email": "justin.trudeau@example.com",
    "designation": "Janitorial staff",
  },
  {
    "memberId": 7,
    "firstName": "George",
    "lastName": "Bush",
    "contact": "732-555-2007",
    "email": "george.bush@example.com",
    "designation": "Janitorial staff",
  },
  {
     "memberId": 8,
    "firstName": "Harry",
    "lastName": "Truman",
    "contact": "732-555-2008",
    "email": "harry.truman@example.com",
    "designation": "Janitorial staff",
  },
  {
     "memberId": 9,
    "firstName": "Dwight",
    "lastName": "Eisenhower",
    "contact": "732-555-2009",
    "email": "dwight.eisenhower@example.com",
    "designation": "Manager",
  },
  {
     "memberId": 10,
    "firstName": "John",
    "lastName": "Adams",
    "contact": "732-555-2010",
    "email": "john.adams@example.com",
    "designation": "Front desk Associate",
  },
  
]